# Generated by Django 2.2 on 2019-04-17 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comuscentia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participation',
        ),
    ]
