# Generated by Django 2.2 on 2019-05-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comuscentia', '0003_auto_20190425_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuscentia.Room'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuscentia.Room')),
            ],
        ),
    ]
