# Generated by Django 2.2.2 on 2019-06-22 22:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comuscentia', '0007_room_msgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='textblock',
            field=tinymce.models.HTMLField(),
        ),
    ]
