# Generated by Django 2.2.2 on 2019-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuscentia', '0009_auto_20190623_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='textblock',
            field=models.TextField(blank=True, default='__To create online-course just fill up this form like written below. You could ask for a course verification later.__\n**Course ID**: \n**Course authors**: \n**Annotation**: \n**University**: \n**Number of study weeks**: _(or start and end dates)_\n**Average load per week**: \n**Educational programs that recognize course learning outcomes**: '),
        ),
    ]
