# Generated by Django 2.2.2 on 2019-06-23 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comuscentia', '0010_auto_20190624_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='verification',
            new_name='verificated',
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuscentia.Room')),
            ],
        ),
    ]
